---
title: "GeneratedFigures"
author: "Venelin Mitov"
date: "3 Jan 2018"
output: pdf_document
keep_md: true
---

```{r setup, include=FALSE}
library(PCMBase)
library(PCMFit)
library(ggtree)
library(ggplot2)
library(data.table)
library(fpc)
library(knitr)
library(rmarkdown)
library(MGPMSimulations)


PCMFit::GeneratePCMModelTypes()

opts_chunk$set(dev='pdf', 
               #results="hide",
               warning=FALSE,
               dev.args=list(
                 family="ArialMT", 
                 pointsize=10,
                 colormodel='rgb'
               ),
               dpi=600, bg='white')

options(PCMBase.Value.NA = -1e20)
options(PCMBase.Lmr.mode = 11)

options(PCMBase.Threshold.SV = 1e-6)

# for 10 simulations there was an eigenvalue below the threshold of 1e-5 for the
# variance covariance transition matrix on 1 node. To calculate the likelihood
# and AIC for these 10 simulations we set the threshold to a more tolerant value.
# In the inference, the threshold will be left as per defaul (i.e. 1e-5).
options(PCMBase.Threshold.EV = 1e-7)
#options(PCMBase.Threshold.EV = 1e-5)

options(PCMBase.Skip.Singular = FALSE)
options(PCMBase.Threshold.Skip.Singular = 1e-4)



evalFig7.2 <- FALSE
evalFig7.3 <- TRUE
```

# Collect inferred models

Here, we extract the inferred model and regimes and add them as columns to the testData_t4 data.table. 

Manual execution.
```{r collect-inferred-models-t4, eval = FALSE}

```

# Evaluate the 7 binary criterions on the inferred models

```{r analyze-simulations-t4, include=FALSE, eval=FALSE}
if(file.exists("../data-raw/ResultsTestData_t4/TestResultData_t4.RData") ) {
  load("../data-raw/ResultsTestData_t4/TestResultData_t4.RData")
} else {
  testResultData <- NULL
}
testResultDataNew <- rbindlist(
  lapply(1:nrow(testData_t4), function(i) {
    
    if(is.null(testResultData) || !(i %in% testResultData[, unique(i)]) ) {
      resultFile <- paste0("../data-raw/ResultsTestData_t4/FinalResult_MixedGaussian_testData_t4_id_", i, "_t4_.RData")

    if(file.exists(resultFile)) {
      cat("Loading ", resultFile, "\n")
      load(resultFile)
      bestFitAIC <- RetrieveBestFitAIC(fitMappings)
      trueFromTestData <- RetrieveTrueFromTestData(testData_t4, i)

      matPredicted_Cluster <- PCMTreeMatrixNodesInSameRegime(bestFitAIC$tree)
      mode(matPredicted_Cluster) <- "double"
      matTRUE_Cluster <- PCMTreeMatrixNodesInSameRegime(trueFromTestData$tree)
      mode(matTRUE_Cluster) <- "double"

      perf_Cluster <- list(tpr = tpr(matPredicted_Cluster, matTRUE_Cluster),
                           fpr = fpr(matPredicted_Cluster, matTRUE_Cluster))

      perf_BM <- list(tpr = tpr(is.BM(bestFitAIC$inferredMappedModels), 
                                is.BM(trueFromTestData$trueMappedModels)),
                      fpr = fpr(is.BM(bestFitAIC$inferredMappedModels), 
                                is.BM(trueFromTestData$trueMappedModels)))
      
      perf_OU <- list(tpr = tpr(is.OU(bestFitAIC$inferredMappedModels), 
                                is.OU(trueFromTestData$trueMappedModels)),
                      fpr = fpr(is.OU(bestFitAIC$inferredMappedModels), 
                                is.OU(trueFromTestData$trueMappedModels)))
      
      perf_Uncorrelated <- list(tpr = tpr(is.Uncorrelated(bestFitAIC$inferredMappedModels),
                                          is.Uncorrelated(trueFromTestData$trueMappedModels)),
                                fpr = fpr(is.Uncorrelated(bestFitAIC$inferredMappedModels),
                                          is.Uncorrelated(trueFromTestData$trueMappedModels)))
      
      perf_Correlated <- list(tpr = tpr(is.Correlated(bestFitAIC$inferredMappedModels),
                                        is.Correlated(trueFromTestData$trueMappedModels)),
                              fpr = fpr(is.Correlated(bestFitAIC$inferredMappedModels),
                                        is.Correlated(trueFromTestData$trueMappedModels)))
      
      perf_NonDiagonalH <- list(tpr = tpr(is.NonDiagonalH(bestFitAIC$inferredMappedModels),
                                          is.NonDiagonalH(trueFromTestData$trueMappedModels)),
                                fpr = fpr(is.NonDiagonalH(bestFitAIC$inferredMappedModels),
                                          is.NonDiagonalH(trueFromTestData$trueMappedModels)))
      
      perf_AsymmetricH <- list(tpr = tpr(is.NonSymmetricH(bestFitAIC$inferredMappedModels),
                                        is.NonSymmetricH(trueFromTestData$trueMappedModels)),
                              fpr = fpr(is.NonSymmetricH(bestFitAIC$inferredMappedModels),
                                        is.NonSymmetricH(trueFromTestData$trueMappedModels)))
      
      
      data.table(i = i,
                 treeType=testData_t4[i, treeType],
                 treeSize=testData_t4[i, treeSize],
                 numClusters = testData_t4[i, numClusters],
                 crit = factor(c("Cluster",
                                 "BM process",
                                 "OU process",
                                 "Uncorrelated traits",
                                 "Correlated traits",
                                 "NonDiagonal H",
                                 "Asymmetric H")
                               ),
                 tpr = c(
                   perf_Cluster$tpr,
                   perf_BM$tpr,
                   perf_OU$tpr,
                   perf_Uncorrelated$tpr,
                   perf_Correlated$tpr,
                   perf_NonDiagonalH$tpr,
                   perf_AsymmetricH$tpr),
                 fpr = c(
                   perf_Cluster$fpr,
                   perf_BM$fpr,
                   perf_OU$fpr,
                   perf_Uncorrelated$fpr,
                   perf_Correlated$fpr,
                   perf_NonDiagonalH$fpr,
                   perf_AsymmetricH$fpr),
                 AIC_Final = AIC(bestFitAIC$inferredModel),
                 AIC_True = AIC(trueFromTestData$trueModel),
                 inferred.x0 = bestFitAIC$inferredModel$X0[[1]],
                 inferred.y0 = bestFitAIC$inferredModel$X0[[2]],
                 true.x0 = trueFromTestData$trueModel$X0[[1]],
                 true.y0 = trueFromTestData$trueModel$X0[[2]]
                 )
    } else {
      NULL
    }
    } else {
      NULL
    }
    
  })
)

if(!is.null(testResultData)) {
  testResultData <- rbindlist(list(testResultData, testResultDataNew), fill = TRUE)
} else {
  testResultData <- testResultDataNew
}

testResultData[, crit2:=factor(crit, levels = c("Cluster",
                                                "BM process",
                                                "OU process",
                                                "Uncorrelated traits",
                                                "Correlated traits",
                                                "NonDiagonal H",
                                                "Asymmetric H"))]

save(testResultData, file="../data-raw/ResultsTestData_t4/TestResultData_t4.RData")
```

```{r analyze-simulations-t4-bhattacharyya, eval=FALSE}
if(file.exists("../data-raw/ResultsTestData_t4/TestResultData_t4.RData") ) {
  load("../data-raw/ResultsTestData_t4/TestResultData_t4.RData")
} else {
  testResultData <- NULL
}

testResultDataBhatt <- rbindlist(
  lapply(1:nrow(testData_t4), function(i) {
    
    
      resultFile <- paste0("../data-raw/ResultsTestData_t4/FinalResult_MixedGaussian_testData_t4_id_", i, "_t4_.RData")

    if(file.exists(resultFile)) {
      cat("Loading ", resultFile, "\n")
      load(resultFile)
      bestFitAIC <- RetrieveBestFitAIC(fitMappings)
      trueFromTestData <- RetrieveTrueFromTestData(testData_t4, i)
      
      bhatt <- bhattacharyya(trueFromTestData$tree, trueFromTestData$trueModel, 
                             bestFitAIC$tree, bestFitAIC$inferredModel)
      
      cat("Bhatt: ", bhatt, "\n")
      data.table(i = i,
                 treeType=testData_t4[i, treeType],
                 treeSize=testData_t4[i, treeSize],
                 numClusters = testData_t4[i, numClusters],
                 crit = factor(c("Bhattacharyya dist.")),
                 tpr = NA,
                 fpr = NA,
                 AIC_Final = AIC(bestFitAIC$inferredModel),
                 AIC_True = AIC(trueFromTestData$trueModel),
                 inferred.x0 = bestFitAIC$inferredModel$X0[[1]],
                 inferred.y0 = bestFitAIC$inferredModel$X0[[2]],
                 true.x0 = trueFromTestData$trueModel$X0[[1]],
                 true.y0 = trueFromTestData$trueModel$X0[[2]],
                 value = bhatt
                 )
    } else {
      NULL
    }
    
  })
)

if(!is.null(testResultData)) {
  testResultData <- rbindlist(list(testResultData, testResultDataNew), fill = TRUE)
} else {
  testResultData <- testResultDataNew
}

testResultData[, crit2:=factor(crit, levels = c("Cluster",
                                                "BM process",
                                                "OU process",
                                                "Uncorrelated traits",
                                                "Correlated traits",
                                                "NonDiagonal H",
                                                "Asymmetric H", 
                                                "Bhattacharyya dist."))]

```

```{r fig7-plot-sim-results-t4, fig.width=8, fig.height=6.66, eval=evalFig7.2}
load("../data-raw/ResultsTestData_t4/TestResultData_t4.RData")
testResultData[, numClusters2:=paste0(numClusters, " regimes")]
testResultData[, treeType2:=factor(paste0(treeType, " tree"), levels=c("ultrametric tree", "non-ultrametric tree"))]
ggplot(testResultData[treeSize == "N=80" & !(crit2 %in% c("BM process", "Uncorrelated traits"))]) +
  geom_abline(slope = 1, intercept = 0, linetype = 2, size = 0.2, color="red") +
  geom_label(aes(label = i, x = fpr, y = tpr,
                 #size = 0.5*apply(cbind((0.2+1-tpr), (0.2+fpr)), 1, max),
                 color = 0.5*apply(cbind((0.2+1-tpr), (0.2+fpr)), 1, max),
                 fill = AIC_Final<AIC_True ),
             size = 2,
             position = position_jitter(width=0.05, height = 0.05),
             label.padding = unit(0.1, "lines"), fontface = "bold") +
  xlab("False positive rate") + ylab("True positive rate") +
  scale_color_continuous(low="green", high="red") +
  scale_fill_manual(values = c("TRUE"="white", "FALSE"="black")) +
  #scale_size_continuous(range = c(1.5, 3)) +
  scale_x_continuous(breaks=c(0, 0.25, 0.5, 0.75, 1)) +
  scale_y_continuous(breaks=c(0, 0.25, 0.5, 0.75, 1)) +
  facet_grid(numClusters2*treeType2~crit2) +
  theme_bw() +
  theme(legend.position = "none")

ggplot(testResultData[treeSize == "N=159" & !(crit2 %in% c("BM process", "Uncorrelated traits"))]) +
  geom_abline(slope = 1, intercept = 0, linetype = 2, size = 0.2, color="red") +
  geom_label(aes(label = i, x = fpr, y = tpr,
                 #size = 0.5*apply(cbind((0.2+1-tpr), (0.2+fpr)), 1, max),
                 color = 0.5*apply(cbind((0.2+1-tpr), (0.2+fpr)), 1, max),
                 fill = AIC_Final<AIC_True ),
             size = 2,
             position = position_jitter(width=0.05, height = 0.05),
             label.padding = unit(0.1, "lines"), fontface = "bold") +
  xlab("False positive rate") + ylab("True positive rate") +
  scale_color_continuous(low="green", high="red") +
  scale_fill_manual(values = c("TRUE"="white", "FALSE"="black")) +
  #scale_size_continuous(range = c(1.5, 3)) +
  scale_x_continuous(breaks=c(0, 0.25, 0.5, 0.75, 1)) +
  scale_y_continuous(breaks=c(0, 0.25, 0.5, 0.75, 1)) +
  facet_grid(numClusters2*treeType2~crit2) +
  theme_bw() +
  theme(legend.position = "none")
```
```{r}
ids <- testData_t4[1:256, list(id = min(.I), .N), keyby=list(treeType, treeSize, numClusters)][, sort(id)]

for(id in ids) {
  print(data.table(
    id = id,
    type = testData_t4$treeType[[id]], 
    size = testData_t4$treeSize[[id]],
    numRegimes = testData_t4$numClusters[[id]]))
  tree <- testData_t4$treeWithRegimes[[id]]
  print(PCMTreeDtNodeRegimes(tree)[endNode <= PCMTreeNumTips(tree), .N, keyby=regime])
}

```

```{r count-num-partitions-x-MGPMs, eval=FALSE}
ids <- testData_t4[1:256, list(id = min(.I), .N), keyby=list(treeType, treeSize)][, sort(id)]

dtNumAllPartitions <- rbindlist(lapply(ids, function(id) {
  data.table(
    id = id,
    type = testData_t4$treeType[[id]], 
    size = testData_t4$treeSize[[id]],
    P18 = data.table(a=sapply(PCMTreeListAllPartitions(
      testData_t4$tree[[id]], 18), length) + 1)[
        , .N, keyby=a][, sum(N*6^a)],
    P19 = data.table(a=sapply(PCMTreeListAllPartitions(
      testData_t4$tree[[id]], 19), length) + 1)[
        , .N, keyby=a][, sum(N*6^a)],
    P20 = data.table(a=sapply(PCMTreeListAllPartitions(
      testData_t4$tree[[id]], 20), length) + 1)[
        , .N, keyby=a][, sum(N*6^a)],
    P21 = data.table(a=sapply(PCMTreeListAllPartitions(
      testData_t4$tree[[id]], 21), length) + 1)[
        , .N, keyby=a][, sum(N*6^a)],
    P22 = data.table(a=sapply(PCMTreeListAllPartitions(
      testData_t4$tree[[id]], 22), length) + 1)[
        , .N, keyby=a][, sum(N*6^a)],
    P23 = data.table(a=sapply(PCMTreeListAllPartitions(
      testData_t4$tree[[id]], 23), length) + 1)[
        , .N, keyby=a][, sum(N*6^a)]
  )
}))

save(dtNumAllPartitions, file = "dtNumAllPartitions.RData")
```

```{r}
load("dtNumAllPartitions.RData")
dtNumAllPartitions
```

```{r fig7-plot-sim-trees-t4, fig.width=6, fig.height=6, eval = TRUE}
ids <- testData_t4[, list(id = min(.I), .N), keyby=list(treeType, treeSize, numClusters)][, sort(id)]

plList <- lapply(ids, function(id) {
  PCMTreePlot(testData_t4$treeWithRegimes[[id]], layout="fan", open.angle=2, size=.25) +
    ggtitle(paste0(LETTERS[match(id, ids)], ". ",
                   testData_t4$treeType[[id]], " / ", 
                   testData_t4$treeSize[[id]], " / ",
                   testData_t4$numClusters[[id]], " regimes"))
})

cowplot::plot_grid(plotlist = plList[1:4], nrow = 2, ncol=2)
cowplot::plot_grid(plotlist = plList[5:8], nrow = 2, ncol=2)
cowplot::plot_grid(plotlist = plList[9:12], nrow = 2, ncol=2)
cowplot::plot_grid(plotlist = plList[13:16], nrow = 2, ncol=2)
```

```{r fig7-scatter-plots-simulations-t4, echo=FALSE, fig.width=9, fig.height=11, eval=evalFig7.3}
data <- rbindlist(lapply(1:nrow(testData_t4), function(i) {
  pl <- PCMPlotTraitData2D(
    X = testData_t4$X[[i]][, 1:PCMTreeNumTips(testData_t4$treeWithRegimes[[i]])],
    tree = testData_t4$treeWithRegimes[[i]])
  cbind(pl$data, testData_t4[i, list(
    rowId = c(i, rep(as.integer(NA), nrow(pl$data)-1)),
    x0 = c(1.0, rep(as.double(NA), nrow(pl$data) - 1)), 
    y0 = c(-1.0, rep(as.double(NA), nrow(pl$data) - 1)), 
    treeType, treeSize, numClusters, clusterNodes, 
    mapping, 
    logLik = c(logLik[[1]], rep(as.double(NA), nrow(pl$data)-1)),
    AIC = c(AIC[[1]], rep(as.double(NA), nrow(pl$data)-1)), 
    nobs = c(nobs[[1]], rep(as.integer(NA), nrow(pl$data)-1)), 
    df = c(df[[1]], rep(as.integer(NA), nrow(pl$data)-1)), 
    IdMappingForClustering, IdParamForMapping, IdSimulationForParam)])
}))

data[, labLogLik:=sapply(logLik, function(ll) if(is.na(ll)) as.character(NA) else paste0("L: ", round(ll, 2)))]
data[, labAIC:=sapply(AIC, function(a) if(is.na(a)) as.character(NA) else paste0("AIC: ", round(a, 2)))]

data[, IdMappingLETTERS:=
       paste0(IdMappingForClustering, ". ", 
              sapply(mapping, function(m) do.call(paste0, as.list(LETTERS[m]))))]

xlim <- c(-15, 15)
ylim <- c(-15, 15)

ggplot(data[treeType == "ultrametric" & treeSize=="N=80" & numClusters==2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  #geom_text(aes(x=-12, y=2, label = labAIC), size = 3, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "ultrametric" & treeSize=="N=80" & numClusters > 2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "ultrametric" & treeSize=="N=159" & numClusters == 2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "ultrametric" & treeSize=="N=159" & numClusters > 2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "ultrametric" & treeSize=="N=318" & numClusters == 2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "ultrametric" & treeSize=="N=318" & numClusters > 2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "ultrametric" & treeSize=="N=638" & numClusters == 2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "ultrametric" & treeSize=="N=638" & numClusters > 2], aes(x, y)) + 
  geom_point(aes(color = regime), size = .1, alpha = .5) +
  geom_point(aes(x=x0, y=y0)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()




ggplot(data[treeType == "non-ultrametric" & treeSize=="N=80" & numClusters==2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "non-ultrametric" & treeSize=="N=80" & numClusters>2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "non-ultrametric" & treeSize=="N=159" & numClusters==2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "non-ultrametric" & treeSize=="N=159" & numClusters>2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "non-ultrametric" & treeSize=="N=318" & numClusters==2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "non-ultrametric" & treeSize=="N=318" & numClusters>2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "non-ultrametric" & treeSize=="N=638" & numClusters==2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()
ggplot(data[treeType == "non-ultrametric" & treeSize=="N=638" & numClusters>2], aes(x, y)) + 
  geom_point(aes(color = regime, size=time, alpha = time)) +
  geom_point(aes(x=x0, y=y0)) +
  scale_size_continuous(range = c(0.05, .5)) +
  scale_alpha_continuous(range = c(0.2, 0.75)) +
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  geom_label(aes(x=-14, y=12, label = rowId), hjust = "left") +
  geom_text(aes(x=-13, y=6, label = labLogLik), size = 2.5, hjust = "left") +
  facet_grid(paste0("Parameter ", IdParamForMapping)+paste0("Simulation ", IdSimulationForParam)~paste0("Mapping ", IdMappingLETTERS)) +
  theme_bw()

```

```{r table-summary-sim-results-t4, eval=FALSE}
load("../data-raw/ResultsTestData_t4/TestResultData_t4.RData")
summaryTable <- testResultData[, {
  maskTests <- !is.na(fpr) & !is.na(tpr)
  numTests <- sum(maskTests)
  list(
    `#tests`=numTests, 
    `Better AIC` = sum(AIC_Final[maskTests] - AIC_True[maskTests] <= 0)/numTests, 
    fpr=sum(fpr[maskTests])/numTests, 
    #`SE(fpr)`=sd(fpr[maskTests])/sqrt(numTests),
    tpr=sum(tpr[maskTests])/numTests#, 
    #`SE(tpr)`=sd(tpr[maskTests])/sqrt(numTests)
    )
},
keyby=list(Crit.=crit2, N=factor(treeSize, levels=c("N=80", "N=159", "N=318", "N=638"), labels=c(80, 159, 318, 638)), 
           `#regimes`=as.integer(numClusters),
           `Tree-type`=factor(treeType, levels=c("ultrametric", "non-ultrametric")))][Crit. %in% c("Cluster", "OU process", "Correlated traits", "NonDiagonal H", "Asymmetric H")]
print.xtable(xtable(summaryTable), comment=FALSE, include.rownames = FALSE)

```

